### ISSUE TITLE
Diseño 1º tipo pregunta de Subsecuencia Comun más larga

### ISSUE THREAD

**Issue by aam0093** [aam0093/Proyecto-Quiz-Prog.-Dinamica#4]

**Comment by aam0093** [comment]
<br><p>Aplique el algoritmo de programación dinámica para determinar la subsecuencia común más larga para las cadenas "ABCBDAB" y "BDCABA", rellenando los valores de la tabla utilizada por el algoritmo.<br></p><br>

<table>
<caption></caption>
<thead>
<tr>
<th scope="col"></th>
<th scope="col">B</th>
<th scope="col">D</th>
<th scope="col">C</th>
<th scope="col">A</th>
<th scope="col">B</th>
<th scope="col">A</th>
</tr>
</thead>
<tbody>
<tr>
<th scope="row">A</th>
<td>{1:SHORTANSWER:%100%0#} </td>
<td>{1:SHORTANSWER:%100%0#} </td>
<td>{1:SHORTANSWER:%100%0#} </td>
<td>{1:SHORTANSWER:%100%1#} </td>
<td>{1:SHORTANSWER:%100%1#} </td>
<td>{1:SHORTANSWER:%100%1#} </td>
</tr>
<tr>
<th scope="row">B</th>
<td>{1:SHORTANSWER:%100%1#} </td>
<td>{1:SHORTANSWER:%100%1#} </td>
<td>{1:SHORTANSWER:%100%1#} </td>
<td>{1:SHORTANSWER:%100%1#} </td>
<td>{1:SHORTANSWER:%100%2#} </td>
<td>{1:SHORTANSWER:%100%2#} </td>
</tr>
<tr>
<th scope="row">C</th>
<td>{1:SHORTANSWER:%100%1#} </td>
<td>{1:SHORTANSWER:%100%1#} </td>
<td>{1:SHORTANSWER:%100%2#} </td>
<td>{1:SHORTANSWER:%100%2#} </td>
<td>{1:SHORTANSWER:%100%2#} </td>
<td>{1:SHORTANSWER:%100%2#} </td>
</tr>
<tr>
<th scope="row">B</th>
<td>{1:SHORTANSWER:%100%1#} </td>
<td>{1:SHORTANSWER:%100%1#} </td>
<td>{1:SHORTANSWER:%100%2#} </td>
<td>{1:SHORTANSWER:%100%2#} </td>
<td>{1:SHORTANSWER:%100%3#} </td>
<td>{1:SHORTANSWER:%100%3#} </td>
</tr>
<tr>
<th scope="row">D</th>
<td>{1:SHORTANSWER:%100%1#} </td>
<td>{1:SHORTANSWER:%100%2#} </td>
<td>{1:SHORTANSWER:%100%2#} </td>
<td>{1:SHORTANSWER:%100%2#} </td>
<td>{1:SHORTANSWER:%100%3#} </td>
<td>{1:SHORTANSWER:%100%3#} </td>
</tr>
<tr>
<th scope="row">A</th>
<td>{1:SHORTANSWER:%100%1#}</td>
<td>{1:SHORTANSWER:%100%2#}</td>
<td>{1:SHORTANSWER:%100%2#}</td>
<td>{1:SHORTANSWER:%100%3#}</td>
<td>{1:SHORTANSWER:%100%3#}</td>
<td>{1:SHORTANSWER:%100%4#}</td>
</tr>
<tr>
<th scope="row">B</th>
<td>{1:SHORTANSWER:%100%1#} </td>
<td>{1:SHORTANSWER:%100%2#} </td>
<td>{1:SHORTANSWER:%100%2#} </td>
<td>{1:SHORTANSWER:%100%3#} </td>
<td>{1:SHORTANSWER:%100%4#} </td>
<td>{1:SHORTANSWER:%100%4#} </td>
</tr>
</tbody>
</table>

<br><br>

**Comment by clopezno** [comment]
![clozesubsecuenciacomun](https://cloud.githubusercontent.com/assets/1453744/6752420/a17cdac0-cf0e-11e4-92fc-c74703ce7ac1.PNG)

Enumero algunas dudas:
¿Hay que incluir algun hiperenlace a la documentación del algoritmo en el enunciado?
¿Cuál es la diferencia entre SHORTANSWER y NUMERICAL en las preguntas Cloze?
Si posible conjunto de valores de salida esta acotado como este ejemplo {1,2,3,4} ¿no es mejor diseñar un la opción MULTICHOICE con diferentes calificaciones para cada opción?

**Comment by aam0093** [comment]
Estoy de acuerdo con que las preguntas deben ser de tipo NUMERICAL, aunque al cambiar el diseño he visto que siguen aceptando caracteres como respuesta, lo interesante sería que eso no sucediese.
En cuanto a la opción de MULTICHOICE  creo que puede ser mas cómodo a la hora de resolver la pregunta con inserción de números ya que con el tabulador podría ser fácil moverse entre las cajas de texto.

**Comment by jjrodriguez** [comment]
En este caso también creo que es mejor que los campos a introducir sean numéricos.

Por otro lado está el tema de obtener la secuencia a partir de los valores de la tabla, por ejemplo "BCBA". Podría ser un campo de texto adicional en la propia pregunta, u otra pregunta 

Un problema es que en ocasiones puede haber varias posibles soluciones válidas. Para el ejemplo, también podría ser "BABA". Podría ser un campo de texto dónde se admitieran como válidas varias respuestas, o un multichoice que incluya alguna correcta y algunas incorrectas, o generar las pregutas de modo que solo haya una solución correcta...

**Comment by clopezno** [comment]
En este [enlace](https://youtu.be/2fOt5rqGQnk) tienes un video con ls revisión de tu trabajo.
Abró una nueva incidencia con para pasar a implementar correctamente ese tipo de pregunta.
